/*
 *       /\        Matteo Cicuttin (C) 2016, 2017, 2018
 *      /__\       matteo.cicuttin@enpc.fr
 *     /_\/_\      École Nationale des Ponts et Chaussées - CERMICS
 *    /\    /\
 *   /__\  /__\    DISK++, a template library for DIscontinuous SKeletal
 *  /_\/_\/_\/_\   methods.
 *
 * This file is copyright of the following authors:
 * Nicolas Pignet  (C) 2026
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 *
 * If you use this code or parts of it for scientific publications, you
 * are required to cite it as following:
 *
 * Hybrid High-Order methods for finite elastoplastic deformations
 * within a logarithmic strain framework.
 * M. Abbas, A. Ern, N. Pignet.
 * International Journal of Numerical Methods in Engineering (2019)
 * 120(3), 303-327
 * DOI: 10.1002/nme.6137
 */

#pragma once

#include "ensight_types.hpp"

#include <filesystem>
#include <fstream>
#include <iomanip>
#include <stdexcept>
#include <vector>

namespace disk::output::ensight {
namespace detail {
template < std::size_t N >
void
write_fixed_elements( std::ostream &os,
                      const char *keyword,
                      const std::vector< std::array< std::int64_t, N > > &elements ) {
    if ( elements.empty() )
        return;
    os << keyword << '\n' << elements.size() << '\n';
    for ( const auto &element : elements ) {
        for ( const auto id : element )
            os << id << ' ';
        os << '\n';
    }
}

inline void
write_main_part( std::ostream &os, const Geometry &g ) {
    os << "part\n"
       << g.part_id << '\n'
       << g.part_name << '\n'
       << "coordinates\n"
       << g.points.size() << '\n';
    for ( const auto &p : g.points )
        os << p[0] << '\n';
    for ( const auto &p : g.points )
        os << p[1] << '\n';
    for ( const auto &p : g.points )
        os << p[2] << '\n';
    write_fixed_elements( os, "bar2", g.bars );
    write_fixed_elements( os, "tria3", g.triangles );
    write_fixed_elements( os, "quad4", g.quadrilaterals );
    if ( !g.polygons.empty() ) {
        os << "nsided\n" << g.polygons.size() << '\n';
        for ( const auto &p : g.polygons )
            os << p.size() << '\n';
        for ( const auto &p : g.polygons ) {
            for ( const auto id : p )
                os << id << ' ';
            os << '\n';
        }
    }
    if ( !g.polyhedra.empty() ) {
        os << "nfaced\n" << g.polyhedra.size() << '\n';
        for ( const auto &c : g.polyhedra )
            os << c.faces.size() << '\n';
        for ( const auto &c : g.polyhedra )
            for ( const auto &f : c.faces )
                os << f.size() << '\n';
        for ( const auto &c : g.polyhedra )
            for ( const auto &f : c.faces ) {
                for ( const auto id : f )
                    os << id << ' ';
                os << '\n';
            }
    }
}

inline void
write_point_cloud_part( std::ostream &os, const PointCloud &cloud ) {
    os << "part\n"
       << cloud.part_id << '\n'
       << cloud.name << '\n'
       << "coordinates\n"
       << cloud.points.size() << '\n';
    for ( const auto &p : cloud.points )
        os << p[0] << '\n';
    for ( const auto &p : cloud.points )
        os << p[1] << '\n';
    for ( const auto &p : cloud.points )
        os << p[2] << '\n';
    os << "point\n" << cloud.points.size() << '\n';
    for ( std::size_t i = 0; i < cloud.points.size(); ++i )
        os << i + 1 << '\n';
}
} // namespace detail

inline void
write_geometry( const std::filesystem::path &path,
                const Geometry &geometry,
                const std::vector< PointCloud > &clouds = {} ) {
    std::ofstream os( path );
    if ( !os )
        throw std::runtime_error( "Cannot open EnSight geometry file: " + path.string() );
    os << std::scientific << std::setprecision( 16 );
    os << "EnSight Gold geometry generated by DiSk++\n"
       << "Static HHO mesh and point clouds\n"
       << "node id assign\n"
       << "element id assign\n";
    detail::write_main_part( os, geometry );
    for ( const auto &cloud : clouds )
        if ( !cloud.points.empty() ) {
            detail::write_point_cloud_part( os, cloud );
        }
}

} // namespace disk::output::ensight
