/*
 *       /\        Matteo Cicuttin (C) 2016, 2017, 2018
 *      /__\       matteo.cicuttin@enpc.fr
 *     /_\/_\      École Nationale des Ponts et Chaussées - CERMICS
 *    /\    /\
 *   /__\  /__\    DISK++, a template library for DIscontinuous SKeletal
 *  /_\/_\/_\/_\   methods.
 *
 * This file is copyright of the following authors:
 * Nicolas Pignet  (C) 2026
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 *
 * If you use this code or parts of it for scientific publications, you
 * are required to cite it as following:
 *
 * Hybrid High-Order methods for finite elastoplastic deformations
 * within a logarithmic strain framework.
 * M. Abbas, A. Ern, N. Pignet.
 * International Journal of Numerical Methods in Engineering (2019)
 * 120(3), 303-327
 * DOI: 10.1002/nme.6137
 */

#pragma once

#include "ensight_types.hpp"

#include <cmath>
#include <cstddef>
#include <filesystem>
#include <fstream>
#include <initializer_list>
#include <iomanip>
#include <stdexcept>
#include <string>
#include <utility>

namespace disk::output::ensight {

inline void
write_point_cloud_geometry( const std::filesystem::path &path, const PointCloud &cloud ) {
    if ( cloud.points.empty() ) {
        throw std::invalid_argument( "Cannot write an empty EnSight point-cloud geometry" );
    }

    std::ofstream os( path );

    if ( !os ) {
        throw std::runtime_error( "Cannot open EnSight point-cloud geometry file: " +
                                  path.string() );
    }

    os << std::scientific << std::setprecision( 16 );

    /*
     * Standard EnSight Gold geometry containing one part
     * composed exclusively of point elements.
     */
    os << "EnSight Gold point-cloud geometry generated by DiSk++\n";
    os << "Gauss-point cloud\n";
    os << "node id assign\n";
    os << "element id assign\n";

    os << "part\n";
    os << "1\n";
    os << cloud.name << '\n';

    os << "coordinates\n";
    os << cloud.points.size() << '\n';

    /*
     * All x coordinates.
     */
    for ( const auto &point : cloud.points ) {
        if ( !std::isfinite( point[0] ) || !std::isfinite( point[1] ) ||
             !std::isfinite( point[2] ) ) {
            throw std::runtime_error( "Non-finite coordinate in EnSight point cloud" );
        }

        os << point[0] << '\n';
    }

    /*
     * All y coordinates.
     */
    for ( const auto &point : cloud.points ) {
        os << point[1] << '\n';
    }

    /*
     * All z coordinates.
     */
    for ( const auto &point : cloud.points ) {
        os << point[2] << '\n';
    }

    /*
     * One point element per coordinate.
     */
    os << "point\n";
    os << cloud.points.size() << '\n';

    for ( std::size_t point_id = 0; point_id < cloud.points.size(); ++point_id ) {
        os << point_id + 1 << '\n';
    }

    /*
     * Add one bar2 element to work around an issue observed with the
     * ParaView EnSight reader when a geometry contains coordinates
     * but no supported non-point element.
     *
     * The remaining Gauss points are intentionally left as isolated
     * nodes. All Gauss-point quantities are exported as nodal fields.
     */
    os << "bar2\n";
    os << 1 << '\n';
    os << 1 << ' ' << 1 << '\n';

    if ( !os ) {
        throw std::runtime_error( "Error while writing EnSight point-cloud geometry: " +
                                  path.string() );
    }
}

template < typename Getter >
void
write_point_cloud_field_streaming( const std::filesystem::path &path,
                                   const std::string &description,
                                   const FieldType type,
                                   const std::size_t point_count,
                                   Getter &&getter ) {
    if ( point_count == 0 ) {
        throw std::invalid_argument( "Cannot write an empty EnSight point cloud field" );
    }

    std::ofstream os( path );

    if ( !os ) {
        throw std::runtime_error( "Cannot open EnSight point cloud field file: " + path.string() );
    }

    os << std::scientific << std::setprecision( 16 );
    os << description << '\n';

    os << "part\n";
    os << "1\n";
    os << "coordinates\n";

    const auto write_component = [&]( const std::size_t component ) {
        for ( std::size_t point_id = 0; point_id < point_count; ++point_id ) {
            const double value = getter( point_id, component );

            if ( !std::isfinite( value ) ) {
                throw std::runtime_error( "Non-finite value in EnSight point cloud field '" +
                                          description + "' at point " + std::to_string( point_id ) +
                                          ", component " + std::to_string( component ) );
            }

            os << value << '\n';
        }
    };

    switch ( type ) {
    case FieldType::scalar:
        write_component( 0 );
        break;

    case FieldType::vector:
        write_component( 0 );
        write_component( 1 );
        write_component( 2 );
        break;

    case FieldType::symmetric_tensor:
        for ( std::size_t component = 0; component < 6; ++component ) {
            write_component( component );
        }
        break;

    case FieldType::tensor:
        for ( const std::size_t component : { 0u, 4u, 8u, 1u, 5u, 6u, 3u, 7u, 2u } ) {
            write_component( component );
        }
        break;
    }

    if ( !os ) {
        throw std::runtime_error( "Error while writing EnSight point cloud field: " +
                                  path.string() );
    }
}

} // namespace disk::output::ensight